CREATE TABLE  DG_ADAPTOR 
(
	 DGC_ID  						CHAR(20) 		NOT NULL,
	 DGC_FK_COMPANY_ID 				CHAR(20)		NOT NULL,
	 DGC_ADAPTOR_GROUP 				VARCHAR2(32)	NOT NULL,
	 DGC_ADAPTOR_NAME 				VARCHAR2(255)	NOT NULL,
	 DGC_STATUS 					INTEGER			NOT NULL,
	 DGC_ADAPTOR_CLASS 				VARCHAR2(255)	NOT NULL,
	 DGC_CREATED_FK_USER_ID  		CHAR(20)		NOT NULL,
	 DGC_CREATED_DATE 	 			TIMESTAMP 		NOT NULL,
	 DGC_UPDATED_FK_USER_ID  		CHAR(20)		NOT NULL,
	 DGC_UPDATED_DATE 	 			TIMESTAMP 		NOT NULL,
	 DGC_COMMENTS 					VARCHAR2(2000)
);