CREATE TABLE DG_ADAPTOR_CONFIG 
(
	 DGC_ID  						CHAR(20) 		NOT NULL,
	 DGC_FK_COMPANY_ID 				CHAR(20)		NOT NULL,
	 DGC_FK_ADAPTOR_ID 				CHAR(20)		NOT NULL,
	 DGC_ADAPTOR_CONFIG_NAME 		VARCHAR2(255)	NOT NULL,
	 DGC_STATUS 					INTEGER			NOT NULL,
	 DGC_ADAPTOR_CONFIG_VALUE 		VARCHAR2(255)	NOT NULL,
	 DGC_CREATED_FK_USER_ID  		CHAR(20)		NOT NULL,
	 DGC_CREATED_DATE 	 			TIMESTAMP 		NOT NULL,
	 DGC_UPDATED_FK_USER_ID  		CHAR(20)		NOT NULL,
	 DGC_UPDATED_DATE 	 			TIMESTAMP 		NOT NULL
);
