CREATE TABLE DG_CONFIG  
(	
	 DGC_ID 							CHAR(20)			NOT NULL,  
	 DGC_DESCRIPTION 					VARCHAR2(255), 
	 DGC_GROUP 							VARCHAR2(255)		NOT NULL, 
	 DGC_PARAM_NAME 					VARCHAR2(255)		NOT NULL, 
	 DGC_PARAM_VALUE 					VARCHAR2(255)		NOT NULL, 
	 DGC_FK_COMPANY_ID 					CHAR(20)			NOT NULL
);
