CREATE TABLE DG_DATA_SOURCE  
(
	 DGC_ID 					    CHAR(20)       	NOT NULL,
	 DGC_FK_COMPANY_ID 			    CHAR(20)		NOT NULL,
	 DGC_NAME 						VARCHAR2(255)  	NOT NULL,
	 DGC_NAME_UPPER 				VARCHAR2(255)  	NOT NULL,
	 DGC_STATUS 					VARCHAR2(16)   	NOT NULL,
	 DGC_TYPE 						VARCHAR2(16)   	NOT NULL,
	 DGC_SUB_TYPE 					VARCHAR2(16),
	 DGC_CREATED_FK_USER_ID 		CHAR(20)		NOT NULL,
	 DGC_CREATED_DATE 				TIMESTAMP 		NOT NULL,
	 DGC_UPDATED_FK_USER_ID 		CHAR(20)		NOT NULL,
	 DGC_UPDATED_DATE 				TIMESTAMP 		NOT NULL,
	 DGC_COMMENTS 					VARCHAR2(2000)
);