CREATE TABLE DG_USER_TIME_PERIOD 
(
	 DGC_ID  							CHAR(20) 		NOT NULL,
	 DGC_FK_COMPANY_ID 					CHAR(20)		NOT NULL,
	 DGC_FK_USER_ID 					CHAR(20)		NOT NULL,
	 DGC_FK_TIME_PERIOD_ID 				CHAR(20)		NOT NULL,
	 DGC_USER_TIME_PERIOD_STATUS 		INTEGER			NOT NULL,
	 DGC_USER_TIME_PERIOD_STATUS_DT 	TIMESTAMP		NOT NULL,
	 DGC_SOURCE_CODE 					INTEGER			NOT NULL,
	 DGC_PERSONNEL_ID              		VARCHAR2(255)   NOT NULL,
	 DGC_EMPLOYEE_KEY 					VARCHAR2(32),
	 DGC_SOURCE_KEY_1 					VARCHAR2(32),
	 DGC_SOURCE_KEY_2 					VARCHAR2(32),
	 DGC_SOURCE_KEY_3 					VARCHAR2(32),
	 DGC_CREATED_FK_USER_ID  			CHAR(20)		NOT NULL,
	 DGC_CREATED_DATE 	 				TIMESTAMP 		NOT NULL,
	 DGC_UPDATED_FK_USER_ID  			CHAR(20)		NOT NULL,
	 DGC_UPDATED_DATE 	 				TIMESTAMP 		NOT NULL,
	 DGC_COMMENTS 						VARCHAR2(2000) 
)
;
