CREATE TABLE DG_USER_LOGIN  
(	
	 DGC_ID 							CHAR(20)			NOT NULL,
	 DGC_FK_COMPANY_ID 					CHAR(20)			NOT NULL,  
	 DGC_ACCESS_TOKEN 					VARCHAR2(255), 
	 DGC_ACTIVE_DATE 					TIMESTAMP, 
	 DGC_AT_CREATED_DATE 				TIMESTAMP, 
	 DGC_AT_EXPERES_IN 					INTEGER, 
	 DGC_EXPIRY_DATE 					TIMESTAMP, 
	 DGC_LAST_LOGIN_DATE 				TIMESTAMP, 
	 DGC_REFRESH_TOKEN 					VARCHAR2(255), 
	 DGC_RT_CREATED_DATE 				TIMESTAMP, 
	 DGC_STATUS 						INTEGER, 
	 DGC_STATUS_DATE 					TIMESTAMP, 
	 DGC_UPDATED_DATE 					TIMESTAMP, 
	 DGC_UPDATED_FK_USER_ID 			VARCHAR2(255), 
	 DGC_USER_AUTH_METHOD 				INTEGER, 
	 DGC_USER_NAME_U 					VARCHAR2(255), 
	 DGC_VERIFICATION_REQ 				INTEGER, 
	 DGC_VERIFIED_DATE 					TIMESTAMP, 
	 DGC_USER_NAME 						VARCHAR2(255), 
	 DGC_USER_PASSWORD 					VARCHAR2(255)
);