CREATE TABLE OAUTH_APPROVALS  
(	
	 USERID 								VARCHAR2(255), 
	 CLIENTID 								VARCHAR2(255), 
	 SCOPE 									VARCHAR2(255), 
	 STATUS 								VARCHAR2(255), 
	 EXPIRESAT 								TIMESTAMP, 
	 LASTMODIFIEDAT 						TIMESTAMP
);
