CREATE TABLE OAUTH_CLIENT_TOKEN  
(	
	 AUTHENTICATION_ID 						VARCHAR2(255)			PRIMARY KEY,
	 TOKEN_ID 								VARCHAR2(255), 
	 TOKEN 									BLOB, 
	 USER_NAME 								VARCHAR2(255), 
	 CLIENT_ID 								VARCHAR2(255)
);
